** Architecture
   nginx is based on:
   - one master process
   - several worker processes
*** Master process
    The main purpose of the master process is to read and evaluate configuration, and maintain worker processes.
*** Worker process
    Worker processes do actual processing of requests. nginx employs event-based model and OS-dependent mechanisms to efficiently distribute requests among worker processes. The number of worker processes is defined in the configuration file and may be fixed for a given configuration or automatically adjusted to the number of available CPU cores (see worker_processes).
** Commands
   - ~service nginx start~
   - ~service nginx restart~
   - ~nginx -s <signal>~
     - ~stop~ — fast shutdown 
     - ~quit~ — graceful shutdown 
     - ~reload~ — reloading the configuration file 
     - ~reopen~ — reopening the log files 
     - ~ps -ax | grep nginx~ - list all running nginx processes
     - [[http://nginx.org/en/docs/control.html][Controlling nginx]]
** Configuration
   - modules (e.g. ~server~)
    - directives
      - simple (e.g. ~listen~)
      - block (e.g. ~location~)
       
#+BEGIN_SRC yaml
server {
   listen 80 default_server;
   root /var/www/[Your repo name]/build;
   server_name [your.domain.com] [your other domain if you want to];
   index index.html index.htm;
   location / {
   }
}
location /files/ { 
   autoindex on;
   root /var/www/[your repo name]/files;
}
#+END_SRC
** Sources
   - [1]: [[http://nginx.org/en/docs/beginners_guide.html][Nginx guide]]

